// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqvxhlolecgacaykxowc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxdnhobG9sZWNnYWNheWt4b3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzEzMTYsImV4cCI6MjA3MDg0NzMxNn0.DR6UPh7A-dYwdyC-4aka4O4_toACcp-oUB_DnMy7NOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});